# DO NOT EDIT THIS FILE

from fabric.api import *
from fabric.contrib.project import rsync_project
from fabric.context_managers import cd

# Other config
env.use_ssh_config = True
env.parallel = True

def deploy_files(execute_flag, local_directory, remote_directory):
	if execute_flag == "True":
		rsync_project(remote_dir=remote_directory, local_dir=local_directory)

def execute_matlab(filename, directory):
	with cd(directory):
		run("matlab -r %s" % filename)
